kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: amqstreams
spec:
  finalizers:
    - kubernetes
status:
  phase: Active

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kafka-operator-group
  namespace: amqstreams
spec:
  targetNamespaces:
  - amqstreams

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: amqstreams
  labels:
    operators.coreos.com/amq-streams.infra-amqstreams: ''  
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.7.0-1

---
kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: cluster-kafka
  namespace: amqstreams
spec:
  kafka:
    authorization:
      superUsers:
        - admin
      type: simple  
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        authentication:
          type: scram-sha-512      
        port: 9093
        type: internal
        tls: true
      - name: external
        authentication:
          type: scram-sha-512
        port: 9094
        type: route
        tls: true        
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.7'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: cluster-kafka
  name: topico
  namespace: amqstreams
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: cluster-kafka
  namespace: amqstreams
spec:
  authentication:
    type: scram-sha-512